[package]
name = "bindcpp"
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx = "0.27.0"
cxx = "1.0.129"

[build-dependencies]
autocxx-build = "0.27.0"
miette = { version = "7.2.0", features = ["fancy"] }
